sudo: false
language: node_js
node_js:
  - "8.0"
  - "9.0"
env:
  - CXX=g++-4.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.3
  hosts:
    - nic.localhost
    - tim.localhost
    - nicola.localhost

cache:
  apt: true
  directories:
    - node_modules
