sudo: false
language: node_js
node_js:
  - "8.0"
  - "10.0"
  - "node"
env:
  matrix:
    - CXX=g++-4.8
    - secure: WM1Hod++b/jUVAZBRRn/8WAPrHQrzILhbE0ubCSyl1kOeyULKbCFpNg82TLbJisg+wSeLrhgbWbYVvW0Bu1rXU9Za7nqWhSwU2EXtjrg3RmRq8WgNcP3cuZq8xYOQ/C6eO3hsysdThkkDnU+M5c+wUvZhVTsMWN8+U2vHfIdjzg=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  hosts:
    - nic.localhost
    - tim.localhost
    - nicola.localhost

before_install:
  - npm install -g npm@latest
  
script:
  - snyk test
  - npm run standard
  - npm run sonar
  - npm run nyc
cache:
  apt: true
  directories:
    - node_modules
notifications:
  email:
  - solid@janeirodigital.com
  - solid-travis@inrupt.com