# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  coopctl:
    docker:
      - image: colabcoop/coopernetes-deploy:0.7.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

jobs:
  deploy:
    executor: coopctl
    steps:
      - checkout
      - setup_remote_docker
      - run: coopctl deploy
  dry-run:
    executor: coopctl
    steps:
      - checkout
      - setup_remote_docker
      - run: coopctl dry-run

workflows:
   deploy:
     jobs:
       - dry-run:
          context: thich-nhat-hanh
          filters:
             branches:
               ignore: develop
       - deploy:
           context: thich-nhat-hanh
           filters:
             branches:
               only: develop
